wifi: rtw89: fix compile error of add support for hardware rfkill
Jenkins compile log shows below:
error: no previous prototype for ‘rtw89_ops_rfkill_poll’
[-Werror=missing-prototypes]
 1101 | void rtw89_ops_rfkill_poll(struct ieee80211_hw *hw)
      |      ^~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Change-Id: I91ef37d0d0e56066e14f5d2839b3b61d44f2015e
Signed-off-by: Dian-Syuan Yang <dian_syuan0116@realtek.com>